name: Chanology
schemes:
  Chanology:
    build:
      targets:
        Chanology: all
        ChanologyTests: [test]
    test:
      targets:
        - ChanologyTests
options:
  bundleIdPrefix: io.mcardle.chanology
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16"
targets:
  Chanology:
    type: application
    platform: iOS
    sources:
      - path: Chanology
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.mcardle.chanology
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Chanology/Info.plist
        DEVELOPMENT_TEAM: ""
    info:
      path: Chanology/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        BGTaskSchedulerPermittedIdentifiers:
          - io.mcardle.chanology.background.refresh
        UIBackgroundModes:
          - fetch
          - remote-notification
        NSUserNotificationsUsageDescription: "Chanology needs notification access to alert you when threads you're watching receive new replies."

  ChanologyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ChanologyTests
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Chanology
