APP_IDENTIFIER = "io.mcardle.chanology"

default_platform :ios

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )

    next_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER
    ) + 1

    build_app(
      scheme: "Chanology",
      sdk: "iphoneos",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      xcargs: "CURRENT_PROJECT_VERSION=#{next_build}",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          APP_IDENTIFIER => "Github Actions profile"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER,
      groups: ["Internal"],
      notify_external_testers: false
    )
  end
end
